function freshState(){return{hero:{weaponLvl:0,armorLvl:0,torchLvl:0,baseAtk:8,baseDef:2,maxHp:50,hp:50,maxSanity:100,sanity:100,maxTorchBonus:0,torchDrainMult:1,goldMult:1,critChance:0.05,sanityResist:0,darkPower:0,revive:0,baseDodge:0,eventRewardMul:1,smithCostMul:1,race:"human"},gold:0,maxDepthRecord:0,bestiary:{},relicsOwned:{},inventory:[],equipment:{weapon:null,head:null,body:null,hands:null,waist:null,feet:null,cloak:null,relic:null},equipSlots:4,bagCapacity:20,activeQuests:[],completedQuestIds:[],questRefreshAt:0,unlockedLayers:[0],selectedLayer:0,unlockedRaces:["human"],craftsMade:0,prayerCooldown:0,activeBlessing:null,warehouse:[],warehouseSlots:20,expedition:{active:false,depth:0,maxDepthReached:0,torch:100,maxTorch:100,monster:null,carriedGold:0,layerIndex:0,itemsFound:[],surviveMinutes:0,surviveTick:0,event:null,skillCooldowns:{},activeBuffs:{},consumables:{},_expeditionEvents:0,bossKilled:[]},lastTs:Date.now(),logs:[]}}

let S=load();
function load(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return freshState();const parsed=JSON.parse(raw);const fresh=freshState();const merged=Object.assign(fresh,parsed,{hero:Object.assign(fresh.hero,parsed.hero||{}),equipment:Object.assign(fresh.equipment,parsed.equipment||{}),expedition:Object.assign(fresh.expedition,parsed.expedition||{})});if(!merged.equipment)merged.equipment={weapon:null,head:null,body:null,hands:null,waist:null,feet:null,cloak:null,relic:null};if(merged.equipment.armor!==undefined&&merged.equipment.body===undefined){merged.equipment.body=merged.equipment.armor||null;delete merged.equipment.armor}if(merged.equipment.accessory1!==undefined){if(!merged.equipment.relic)merged.equipment.relic=merged.equipment.accessory1||null;delete merged.equipment.accessory1}if(merged.equipment.accessory2!==undefined){merged.inventory=merged.inventory||[];if(merged.equipment.accessory2)merged.inventory.push(merged.equipment.accessory2);delete merged.equipment.accessory2}["head","hands","waist","feet","cloak"].forEach(k=>{if(!(k in merged.equipment))merged.equipment[k]=null});if(merged.equipSlots===undefined||merged.equipSlots<4)merged.equipSlots=4;if(merged.bagCapacity===undefined)merged.bagCapacity=20;if(merged.prayerCooldown===undefined)merged.prayerCooldown=0;if(merged.activeBlessing===undefined)merged.activeBlessing=null;if(!merged.warehouse)merged.warehouse=[];if(merged.warehouseSlots===undefined)merged.warehouseSlots=20;if(!merged.activeQuests)merged.activeQuests=[];if(!merged.unlockedLayers)merged.unlockedLayers=[0];if(!merged.selectedLayer)merged.selectedLayer=0;
    if(!merged.unlockedRaces)merged.unlockedRaces=["human"];if(merged.craftsMade===undefined)merged.craftsMade=0;if(!merged.questRefreshAt)merged.questRefreshAt=0;if(!merged.completedQuestIds)merged.completedQuestIds=[];if(merged.expedition&&merged.expedition.maxDepthReached===undefined)merged.expedition.maxDepthReached=0;if(merged.expedition&&merged.expedition.itemsFound===undefined)merged.expedition.itemsFound=[];if(merged.expedition&&merged.expedition.surviveTick===undefined)merged.expedition.surviveTick=0;if(!merged.hero.race)merged.hero.race="human";if(merged.hero.baseDodge===undefined)merged.hero.baseDodge=0;if(merged.hero.eventRewardMul===undefined)merged.hero.eventRewardMul=1;if(merged.hero.smithCostMul===undefined)merged.hero.smithCostMul=1;return merged}catch(e){return freshState()}}
function save(){if(S._deleting||S._inRaceSelect)return;S.lastTs=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(S))}
function el(id){return document.getElementById(id)}

/* ========== 种族数据 ========== */
function calcHeroStats(){const h=S.hero,eq=S.equipment;let atk=h.baseAtk,def=h.baseDef,maxHp=h.maxHp;let crit=h.critChance,torchSave=0,sanityResist=h.sanityResist||0;let goldMul=h.goldMult,darkPower=h.darkPower||0,revive=h.revive||0;let dodge=h.baseDodge||0,bagSlots=0,spawnReduce=0,healOnKill=0,maxSanityBonus=0;Object.values(eq).forEach(item=>{if(!item||item.durability<=0)return;const s=item.stats;if(s.atk)atk+=s.atk;if(s.def)def+=s.def;if(s.maxHp)maxHp+=s.maxHp;if(s.crit)crit+=s.crit;if(s.torchSave)torchSave+=s.torchSave;if(s.sanityResist)sanityResist+=s.sanityResist;if(s.goldMult)goldMul+=s.goldMult;if(s.darkPower)darkPower+=s.darkPower;if(s.revive)revive+=s.revive;if(s.dodge)dodge+=s.dodge;if(s.bagSlots)bagSlots+=s.bagSlots;if(s.spawnReduce)spawnReduce+=s.spawnReduce;if(s.healOnKill)healOnKill+=s.healOnKill;if(s.maxSanity)maxSanityBonus+=s.maxSanity});const result={atk,def,maxHp,crit,torchSave,sanityResist,goldMul,darkPower,revive,dodge,bagSlots,spawnReduce,healOnKill,maxSanityBonus,torchBlessingMul:1};if(S.activeBlessing)S.activeBlessing.apply(result);return result}
function getBagCapacity(){const s=calcHeroStats();return S.bagCapacity+s.bagSlots}
function heroMaxTorchBase(){return 100+S.hero.maxTorchBonus}
function pushLog(text,cls){S.logs.unshift({text,cls:cls||""});if(S.logs.length>80)S.logs.length=80}
function generateItem(depth,layerIdx){const roll=Math.random();if(roll<0.60)return generateMaterial(depth,layerIdx);if(roll<0.90)return generateEquip(depth,layerIdx,false);return generateEquip(depth,layerIdx,true)}
function generateMaterial(depth,layerIdx){const maxRarityIdx=Math.min(4,Math.floor(layerIdx/1)+1);const avail=MATERIAL_TEMPLATES.filter(m=>["common","uncommon","rare","epic","legendary"].indexOf(m.rarity)<=maxRarityIdx);const tpl=avail[Math.floor(Math.random()*avail.length)];return{id:tpl.id+"_"+Date.now()+"_"+Math.random().toString(36).slice(2,6),templateId:tpl.id,name:tpl.name,type:"material",rarity:tpl.rarity,stats:{},durability:999,maxDurability:999,sellPrice:Math.round(tpl.baseVal*(0.85+Math.random()*0.3)),unidentified:false}}
function generateEquip(depth,layerIdx,unidentified){const maxRarityIdx=Math.min(4,Math.floor(layerIdx/1)+1);const avail=EQUIP_TEMPLATES.filter(e=>["common","uncommon","rare","epic","legendary"].indexOf(e.rarity)<=maxRarityIdx);const tpl=avail[Math.floor(Math.random()*avail.length)];const dur=Math.round(tpl.baseDura*(0.7+Math.random()*0.6));const stats={};Object.entries(tpl.baseStats).forEach(([k,v])=>{stats[k]=v});return{id:tpl.id+"_"+Date.now()+"_"+Math.random().toString(36).slice(2,6),templateId:tpl.id,name:unidentified?"未鉴定的装备":tpl.name,type:tpl.type,rarity:tpl.rarity,stats,durability:dur,maxDurability:dur,sellPrice:Math.round(tpl.baseVal*(0.85+Math.random()*0.3)),unidentified}}
function checkBossSpawn(depth,layerIdx,darkness){for(const b of BOSSES){if(b.layer!==layerIdx||S.expedition.bossKilled.includes(b.id))continue;if(b.hidden){if(b.spawnCond==="darkness>0.8"&&darkness>0.8&&depth>=b.triggerDepth&&Math.random()<0.02)return generateBoss(b,depth,layerIdx)}else if(depth>=b.triggerDepth&&Math.random()<0.03)return generateBoss(b,depth,layerIdx)}return null}
function generateBoss(boss,depth,layerIdx){const hpBase=14+layerIdx*10;const atkBase=3+layerIdx*2.4;return{name:boss.name,hp:Math.round(hpBase*(1+depth*0.03)*boss.hpMul),maxHp:Math.round(hpBase*(1+depth*0.03)*boss.hpMul),atk:Math.round(atkBase*(1+depth*0.03)*boss.atkMul),goldMul:1,special:boss.special,isBoss:true,bossId:boss.id}}
function pickMonster(depth,layerIdx){const layer=LAYERS[layerIdx];let pool=layer.monsters;if(layerIdx===0)pool=pool.filter(m=>depth>=m.depthMin&&depth<=m.depthMax);if(pool.length===0)pool=layer.monsters;const tw=pool.reduce((s,m)=>s+(m.weight||10),0);let r=Math.random()*tw;for(const m of pool){r-=(m.weight||10);if(r<=0){const n=m.name,hmu=m.hpMul||1,amu=m.atkMul||1,gmu=m.goldMul||1,sp=m.special||null;const sc=1+(depth-layer.startDepth)*0.04+Math.random()*0.15;const hb=14+layerIdx*10,ab=3+layerIdx*2.4;return{name:n,hp:Math.round(hb*sc*hmu),maxHp:Math.round(hb*sc*hmu),atk:Math.round(ab*sc*amu),goldMul:gmu,special:sp}}}return{name:pool[0].name,hp:10,maxHp:10,atk:3,goldMul:1,special:null}}
function spotLine(depth){const layer=LAYERS.find(l=>depth>=l.startDepth&&depth<l.maxDepth)||LAYERS[LAYERS.length-1];return layer.spot[Math.floor(Math.random()*layer.spot.length)]}
function pickGoblinOrMonster(depth,layerIdx){if(layerIdx===0&&Math.random()<0.03){const tw=GOBLINS.reduce((s,g)=>s+g.weight,0);let r=Math.random()*tw;for(const g of GOBLINS){r-=g.weight;if(r<=0){const sc=1+depth*0.03;const hb=14,ab=3;return{name:g.name,hp:Math.round(hb*sc*g.hpMul),maxHp:Math.round(hb*sc*g.hpMul),atk:Math.round(ab*sc*g.atkMul),goldMul:g.goldMul,special:g.special,isGoblin:true,goblinData:g}}}return pickMonster(depth,layerIdx)}return pickMonster(depth,layerIdx)}
function processMonsterDrops(m,ex,depth){const layer=LAYERS[ex.layerIndex];const mon=layer.monsters.find(x=>x.name===m.name);if(!mon||!mon.drops)return;mon.drops.forEach(d=>{if(Math.random()<d.chance){const tpl=MATERIAL_TEMPLATES.find(t=>t.id===d.mid);if(tpl){const qty=d.qty||1;for(let i=0;i<qty;i++){const item={id:tpl.id+"_"+Date.now()+"_"+Math.random().toString(36).slice(2,6),templateId:tpl.id,name:tpl.name,type:"material",rarity:tpl.rarity,stats:{},durability:999,maxDurability:999,sellPrice:tpl.baseVal,unidentified:false};ex.itemsFound.push(item)}}}})}
function processGoblinDrops(g,ex){if(!g.drops)return;g.drops.forEach(d=>{if(Math.random()<d.chance){const tpl=MATERIAL_TEMPLATES.find(t=>t.id===d.mid);if(tpl){const qty=d.qty||1;for(let i=0;i<qty;i++){const item={id:tpl.id+"_goblin_"+Date.now()+"_"+Math.random().toString(36).slice(2,6),templateId:tpl.id,name:tpl.name,type:"material",rarity:tpl.rarity,stats:{},durability:999,maxDurability:999,sellPrice:tpl.baseVal,unidentified:false};ex.itemsFound.push(item)}}}});if(g.equipDrop){const rarity=g.equipDrop===true?"uncommon":g.equipDrop;const pool=EQUIP_TEMPLATES.filter(e=>e.rarity===rarity&&!e.bossEquip);if(pool.length>0){const tpl=pool[Math.floor(Math.random()*pool.length)];const item=generateEquipFromTpl(tpl);ex.itemsFound.push(item);pushLog(`🪙 地精掉落了 ${item.name}！`,"good")}}}
function generateEquipFromTpl(tpl){const dur=Math.round(tpl.baseDura*(0.7+Math.random()*0.6));return{id:tpl.id+"_gob_"+Date.now()+"_"+Math.random().toString(36).slice(2,6),templateId:tpl.id,name:tpl.name,type:tpl.type,rarity:tpl.rarity,stats:{...tpl.baseStats},durability:dur,maxDurability:dur,sellPrice:tpl.baseVal,unidentified:false}}
function dropBossEquip(m,ex){const pool=BOSS_EQUIP_POOL[m.bossId];if(!pool)return;const tid=pool[Math.floor(Math.random()*pool.length)];const tpl=EQUIP_TEMPLATES.find(e=>e.id===tid);if(!tpl)return;const item=generateEquipFromTpl(tpl);item.unidentified=true;item.name="未鉴定的装备";ex.itemsFound.push(item);pushLog(`🏆 ${m.name}掉落了一件未鉴定的装备！`,"good")}

function startExpedition(layerIdx){const layer=LAYERS[layerIdx];const stats=calcHeroStats();S.hero.hp=stats.maxHp;const savedConsumables=S.expedition.consumables||{};S.expedition={active:true,depth:layer.startDepth,maxDepthReached:layer.startDepth,torch:heroMaxTorchBase(),maxTorch:heroMaxTorchBase(),monster:null,carriedGold:0,layerIndex:layerIdx,itemsFound:[],surviveMinutes:0,surviveTick:0,event:null,skillCooldowns:{},activeBuffs:{},consumables:savedConsumables,_expeditionEvents:0,bossKilled:[]};pushLog(`你踏入${layer.name}，火把照亮前方……`,"dim");switchToExpedition();render();save()}

function unlockRace(raceId){if(!S.unlockedRaces.includes(raceId)){S.unlockedRaces.push(raceId);const r=RACES.find(x=>x.id===raceId);if(r)pushLog(`🏆 新的守望者已觉醒——${r.icon} ${r.name}：${r.title}`,"good")}}
function checkLayerUnlock(layerIdx,maxDepth){if(maxDepth>=LAYERS[layerIdx].maxDepth&&layerIdx+1<LAYERS.length&&!S.unlockedLayers.includes(layerIdx+1)){S.unlockedLayers.push(layerIdx+1);const next=LAYERS[layerIdx+1];pushLog(`深渊之门震颤——${next.name}已向你敞开！`,"good");if(next.unlockBonus)pushLog(next.unlockBonus,"good");if(layerIdx+1===1)S.equipSlots=6;if(layerIdx+1===2)S.equipSlots=7;if(layerIdx+1===3)S.equipSlots=8}for(let i=layerIdx+1;i<LAYERS.length;i++){if(maxDepth>=LAYERS[i-1].maxDepth&&!S.unlockedLayers.includes(i)){S.unlockedLayers.push(i);pushLog(`深渊之门震颤——${LAYERS[i].name}已向你敞开！`,"good");if(i===1)S.equipSlots=Math.max(S.equipSlots,6);if(i===2)S.equipSlots=Math.max(S.equipSlots,7);if(i===3)S.equipSlots=Math.max(S.equipSlots,8)}}}

function updateQuestKill(monsterName){S.activeQuests.forEach(q=>{if(q.type==="kill"&&q.monster===monsterName)q.progress=Math.min(q.count,(q.progress||0)+1)})}
function updateQuestOnEnd(ex){S.activeQuests.forEach(q=>{if(q.type==="depth"&&ex.maxDepthReached>=q.target)q.progress=q.count||1;if(q.type==="survive"&&ex.surviveMinutes>=q.minutes)q.progress=q.count||1;if(q.type==="collect"){const found=ex.itemsFound.filter(i=>i.name===q.material).length;q.progress=Math.min(q.count,(q.progress||0)+found)}})}
function checkQuestCompletion(){S.activeQuests=S.activeQuests.filter(q=>{if(q.expiresAt&&q.expiresAt<Date.now()&&!q.completed){pushLog(`任务「${q.name}」已过期。`,"dim");return false}return true});S.activeQuests.forEach(q=>{if(!q.completed&&q.progress>=(q.count||1))q.completed=true})}
function generateQuest(){const now=Date.now();const available=QUEST_POOL.filter(q=>{if(S.activeQuests.find(aq=>aq.poolId===q.id))return false;if(q.needLayer&&!S.unlockedLayers.includes(q.needLayer))return false;return true});if(available.length===0)return null;const tpl=available[Math.floor(Math.random()*available.length)];return{poolId:tpl.id,name:tpl.name,desc:tpl.desc,type:tpl.type,monster:tpl.monster||null,count:tpl.count||1,target:tpl.target||0,material:tpl.material||null,minutes:tpl.minutes||0,progress:0,completed:false,reward:{gold:tpl.gold,itemTid:tpl.itemReward?tpl.itemReward.tid:null},expiresAt:now+(tpl.timeLimit||15)*60*1000,needLayer:tpl.needLayer||0}}
function claimQuest(q){if(!q.completed)return;S.gold+=q.reward.gold;pushLog(`完成任务「${q.name}」，获得 ${q.reward.gold} 金。`,"good");if(q.reward.itemTid){const tpl=EQUIP_TEMPLATES.find(e=>e.id===q.reward.itemTid);if(tpl&&S.inventory.length<getBagCapacity()){const item={id:tpl.id+"_quest_"+Date.now()+"_"+Math.random().toString(36).slice(2,6),templateId:tpl.id,name:tpl.name,type:tpl.type,rarity:tpl.rarity,stats:{...tpl.baseStats},durability:tpl.baseDura,maxDurability:tpl.baseDura,sellPrice:tpl.baseVal,unidentified:false};S.inventory.push(item);pushLog(`获得了 ${tpl.name}！`,"good")}}S.completedQuestIds.push(q.poolId);S.activeQuests=S.activeQuests.filter(aq=>aq!==q);S.questRefreshAt=Date.now()+2*60*1000}
function refreshQuests(){if(S.activeQuests.length>=3)return;const need=3-S.activeQuests.length;for(let i=0;i<need;i++){const q=generateQuest();if(q)S.activeQuests.push(q)}}

function switchToCamp(){document.body.classList.remove("in-expedition");renderCampTab(S._campTab||"prep")}
function switchToExpedition(){document.body.classList.add("in-expedition")}
