"use strict";
const SAVE_KEY = "zhuzhao_youyuan_save_v2";
const RARITY={common:{name:"普通",color:"var(--common)",sellMul:1,craftCostMul:1,idMul:1},uncommon:{name:"精良",color:"var(--uncommon)",sellMul:2.5,craftCostMul:2,idMul:2.5},rare:{name:"稀有",color:"var(--rare)",sellMul:6,craftCostMul:4,idMul:6},epic:{name:"史诗",color:"var(--epic)",sellMul:15,craftCostMul:8,idMul:12},legendary:{name:"传说",color:"var(--legendary)",sellMul:40,craftCostMul:20,idMul:25}};
const EQUIP_TEMPLATES=[
{id:"rusty_sword",name:"锈剑",type:"weapon",rarity:"common",baseStats:{atk:3},baseDura:90,baseVal:15},{id:"hunting_axe",name:"猎斧",type:"weapon",rarity:"common",baseStats:{atk:4,def:-1},baseDura:80,baseVal:18},{id:"ritual_dagger",name:"仪式匕首",type:"weapon",rarity:"uncommon",baseStats:{atk:5,crit:0.03},baseDura:75,baseVal:35},{id:"blessed_blade",name:"祝福长剑",type:"weapon",rarity:"rare",baseStats:{atk:8,crit:0.05},baseDura:100,baseVal:80},{id:"soul_reaper",name:"夺魂之镰",type:"weapon",rarity:"epic",baseStats:{atk:12,crit:0.08},baseDura:120,baseVal:200},{id:"abyss_edge",name:"深渊之锋",type:"weapon",rarity:"legendary",baseStats:{atk:18,crit:0.12},baseDura:150,baseVal:500},
{id:"cloth_hood",name:"布兜帽",type:"head",rarity:"common",baseStats:{sanityResist:0.05},baseDura:70,baseVal:10},{id:"iron_helm",name:"铁盔",type:"head",rarity:"uncommon",baseStats:{def:2,sanityResist:0.08},baseDura:100,baseVal:25},{id:"silver_circlet",name:"银冠",type:"head",rarity:"rare",baseStats:{sanityResist:0.15,maxSanity:10},baseDura:90,baseVal:60},{id:"void_crown",name:"虚空之冠",type:"head",rarity:"epic",baseStats:{sanityResist:0.22,darkPower:0.08},baseDura:110,baseVal:160},
{id:"leather_vest",name:"皮革背心",type:"body",rarity:"common",baseStats:{def:2,maxHp:8},baseDura:100,baseVal:12},{id:"chainmail",name:"锁子甲",type:"body",rarity:"uncommon",baseStats:{def:4,maxHp:15},baseDura:120,baseVal:30},{id:"iron_plate",name:"铁板铠",type:"body",rarity:"rare",baseStats:{def:6,maxHp:25},baseDura:150,baseVal:70},{id:"blessed_robe",name:"祝福长袍",type:"body",rarity:"epic",baseStats:{def:3,maxHp:20,sanityResist:0.1},baseDura:100,baseVal:160},{id:"abyss_cage",name:"深渊囚笼",type:"body",rarity:"legendary",baseStats:{def:10,maxHp:40,darkPower:0.15},baseDura:180,baseVal:420},
{id:"worn_gloves",name:"旧手套",type:"hands",rarity:"common",baseStats:{crit:0.02},baseDura:60,baseVal:8},{id:"iron_gauntlets",name:"铁护手",type:"hands",rarity:"uncommon",baseStats:{atk:2,crit:0.04},baseDura:80,baseVal:22},{id:"shadow_bracers",name:"暗影护腕",type:"hands",rarity:"rare",baseStats:{atk:3,crit:0.07},baseDura:90,baseVal:55},{id:"fate_grip",name:"命运之握",type:"hands",rarity:"epic",baseStats:{atk:5,crit:0.10},baseDura:100,baseVal:150},
{id:"rope_belt",name:"绳带",type:"waist",rarity:"common",baseStats:{bagSlots:3},baseDura:80,baseVal:12},{id:"leather_belt",name:"皮带",type:"waist",rarity:"uncommon",baseStats:{bagSlots:5},baseDura:90,baseVal:28},{id:"pouch_girdle",name:"囊袋腰带",type:"waist",rarity:"rare",baseStats:{bagSlots:8,goldMult:0.05},baseDura:100,baseVal:55},{id:"abyss_sash",name:"渊带",type:"waist",rarity:"epic",baseStats:{bagSlots:12,goldMult:0.10},baseDura:110,baseVal:140},
{id:"old_boots",name:"旧靴",type:"feet",rarity:"common",baseStats:{dodge:0.03},baseDura:80,baseVal:10},{id:"iron_greaves",name:"铁胫甲",type:"feet",rarity:"uncommon",baseStats:{def:1,dodge:0.05},baseDura:100,baseVal:24},{id:"silent_sandals",name:"消声便鞋",type:"feet",rarity:"rare",baseStats:{dodge:0.08,spawnReduce:0.10},baseDura:80,baseVal:50},{id:"shadow_striders",name:"影行之靴",type:"feet",rarity:"epic",baseStats:{dodge:0.12,spawnReduce:0.18},baseDura:90,baseVal:140},
{id:"torn_cloak",name:"破旧披风",type:"cloak",rarity:"common",baseStats:{torchSave:0.06},baseDura:70,baseVal:10},{id:"waxed_mantle",name:"蜡浸斗篷",type:"cloak",rarity:"uncommon",baseStats:{torchSave:0.12},baseDura:80,baseVal:25},{id:"shadow_shroud",name:"暗影裹尸布",type:"cloak",rarity:"rare",baseStats:{torchSave:0.10,darkPower:0.12},baseDura:90,baseVal:58},{id:"flame_cloak",name:"不灭之焰",type:"cloak",rarity:"epic",baseStats:{torchSave:0.20,maxTorchBonus:10},baseDura:100,baseVal:155},
{id:"bone_charm",name:"骨符",type:"relic",rarity:"common",baseStats:{atk:1,def:1},baseDura:50,baseVal:12},{id:"candle_ember",name:"烛火余烬",type:"relic",rarity:"uncommon",baseStats:{torchSave:0.05,healOnKill:2},baseDura:55,baseVal:30},{id:"void_eye",name:"虚空之眼",type:"relic",rarity:"rare",baseStats:{crit:0.05,darkPower:0.10},baseDura:60,baseVal:65},{id:"phoenix_feather",name:"凤凰翎羽",type:"relic",rarity:"legendary",baseStats:{revive:1,healOnKill:5},baseDura:50,baseVal:600}];
const MATERIAL_TEMPLATES=[{id:"bone_shard",name:"骨片",rarity:"common",baseVal:3},{id:"soul_ember",name:"魂火余烬",rarity:"uncommon",baseVal:8},{id:"dark_iron",name:"暗铁碎片",rarity:"rare",baseVal:22},{id:"abyss_essence",name:"深渊精华",rarity:"epic",baseVal:65},{id:"ancient_core",name:"古渊之核",rarity:"legendary",baseVal:200}];
const LAYERS=[
{index:0,name:"浅层回廊",startDepth:0,maxDepth:70,monsters:[{name:"巨鼠",hpMul:0.7,atkMul:0.8,goldMul:1.0,special:"split_chance"},{name:"洞穴蝠",hpMul:0.5,atkMul:1.1,goldMul:0.8,special:"dodge15"},{name:"苔衣尸",hpMul:1.3,atkMul:0.6,goldMul:1.2,special:"regen"},{name:"白骨犬",hpMul:0.9,atkMul:1.4,goldMul:0.9,special:"pierce"},{name:"断指盗",hpMul:0.8,atkMul:0.9,goldMul:1.5,special:"bonusGold"},{name:"石肤蜥蜴",hpMul:1.5,atkMul:0.5,goldMul:1.0,special:"armor3"},{name:"腐泥怪",hpMul:1.8,atkMul:0.4,goldMul:1.1,special:"split"},{name:"暗影爬行者",hpMul:0.6,atkMul:1.3,goldMul:1.3,special:"darkOnly"},{name:"尖啸之颅",hpMul:0.5,atkMul:0.7,goldMul:0.7,special:"sanityDmg"},{name:"缚灵侍女",hpMul:1.0,atkMul:1.0,goldMul:1.2,special:"narrative"},{name:"深渊血蛭",hpMul:0.7,atkMul:0.9,goldMul:1.0,special:"lifesteal"},{name:"锈蚀哨兵",hpMul:2.0,atkMul:0.7,goldMul:1.3,special:"blockCrit"},{name:"暗影刺客",hpMul:0.4,atkMul:1.8,goldMul:1.5,special:"dodge20"},{name:"熔火幼兽",hpMul:1.2,atkMul:1.2,goldMul:1.0,special:"fireDmg"},{name:"低语信徒",hpMul:0.8,atkMul:0.8,goldMul:1.4,special:"sanityDrainAura"}],spot:["黑暗���传来窸窣爬行声…","脚下的碎骨咯吱作响。","有什么东西正在墙角窥视你。"],danger:"⚔️",unlockMsg:null,unlockBonus:null},
{index:1,name:"中层甬道",startDepth:70,maxDepth:160,monsters:[{name:"锈甲卫",hpMul:1.0,atkMul:1.0,goldMul:1.0},{name:"低语尸祝",hpMul:1.0,atkMul:1.0,goldMul:1.0},{name:"石隙蛛",hpMul:1.0,atkMul:1.0,goldMul:1.0},{name:"断头骑士",hpMul:1.0,atkMul:1.0,goldMul:1.0},{name:"缚魂傀儡",hpMul:1.0,atkMul:1.0,goldMul:1.0}],spot:["甲胄摩擦的声响由远及近。","低语声顺着石缝钻进耳中。","空气开始发涩，带着铁锈味。"],danger:"⚔️⚔️",unlockMsg:"曾到达浅层回廊最深处（70尺）",unlockBonus:"头部+腰部槽位解锁"},
{index:2,name:"深层墓室",startDepth:160,maxDepth:280,monsters:[{name:"影食者",hpMul:1.0,atkMul:1.0,goldMul:1.0},{name:"泣血修女",hpMul:1.0,atkMul:1.0,goldMul:1.0},{name:"无面祭司",hpMul:1.0,atkMul:1.0,goldMul:1.0},{name:"深渊触手",hpMul:1.0,atkMul:1.0,goldMul:1.0},{name:"铁笼囚魂",hpMul:1.0,atkMul:1.0,goldMul:1.0}],spot:["空气骤然发冷，低语萦绕耳畔。","你的影子似乎慢了半拍。","某种目光穿透了黑暗。"],danger:"⚔️⚔️⚔️",unlockMsg:"曾到达中层甬道最深处（160尺）",unlockBonus:"披风槽位解锁"},
{index:3,name:"绝渊回廊",startDepth:280,maxDepth:999,monsters:[{name:"王座囚魂",hpMul:1.0,atkMul:1.0,goldMul:1.0},{name:"古渊之眼",hpMul:1.0,atkMul:1.0,goldMul:1.0},{name:"弃神残躯",hpMul:1.0,atkMul:1.0,goldMul:1.0},{name:"永夜使者",hpMul:1.0,atkMul:1.0,goldMul:1.0},{name:"万骨之影",hpMul:1.0,atkMul:1.0,goldMul:1.0}],spot:["整条回廊仿佛屏住了呼吸。","连火光都在退缩。","这里没有回声，只有等待。"],danger:"⚔️⚔️⚔️⚔️",unlockMsg:"曾到达深层墓室最深处（280尺）",unlockBonus:"圣物槽位+酒馆解锁"}];
const EXPLORATION_EVENTS=[{type:"curio",name:"古老烛台",layers:[0,1,2,3],safe:{text:"点燃残烛",effect:"torch",val:18,log:"烛光陡然明亮，火把恢复了些许。"},risky:{text:"刮取烛泪",effect:"gold",val:35,riskChance:0.25,riskEffect:"sanityPenalty",riskVal:8,log:"烛泪中凝着古老的金粉，值些钱。",riskLog:"烛泪溅到手上，灼痛直钻骨髓……"}},{type:"curio",name:"封尘的书架",layers:[1,2,3],safe:{text:"整理书籍",effect:"sanity",val:10,log:"翻阅古籍让心神平静。"},risky:{text:"撕下书页",effect:"relic_chance",val:0.15,riskChance:0.35,riskEffect:"curse_spawn",riskVal:0,log:"书页间夹着一张泛黄的护符！",riskLog:"撕书声在回廊中回荡……什么东西被惊醒了。"}},{type:"curio",name:"锈蚀的铁棺",layers:[2,3],safe:{text:"保持距离",effect:"torch",val:10,log:"你远远绕开了铁棺。"},risky:{text:"撬开棺盖",effect:"equip_drop",val:1,riskChance:0.4,riskEffect:"hpLoss",riskVal:15,log:"棺中躺着一件完好的装备！",riskLog:"棺中窜出毒雾，呛得你连连后退。"}},{type:"trap",name:"塌陷的石板",layers:[0,1,2,3],safe:{text:"绕行",effect:"depth_cost",val:0.6,log:"你多绕了一段路。"},risky:{text:"跳过去",effect:"skip",val:0,riskChance:0.3,riskEffect:"hpLoss",riskVal:10,log:"你稳稳落地。",riskLog:"石板碎裂，你跌了一跤。"}},{type:"trap",name:"蛛网密布的窄道",layers:[0,1,2,3],safe:{text:"烧掉蛛网",effect:"torch_cost",val:8,log:"火把烧尽了蛛网。"},risky:{text:"挤过去",effect:"gold",val:25,riskChance:0.35,riskEffect:"sanityPenalty",riskVal:12,log:"蛛网后藏着一小堆金币！",riskLog:"蛛丝黏在皮肤上，细碎的爬行感久久不散……"}},{type:"trap",name:"低语的裂隙",layers:[1,2,3],safe:{text:"捂住耳朵",effect:"skip",val:0,log:"你快步通过了裂隙。"},risky:{text:"凑近倾听",effect:"knowledge_fragment",val:1,riskChance:0.4,riskEffect:"sanityPenalty",riskVal:20,log:"你听懂了一个古老的名字……",riskLog:"低语灌入脑中，头像要裂开一般。"}},{type:"narrative",text:"墙上的刻字：『第四个已经死了，而我还在数。』",effect:"sanityPenalty",val:3,layers:[0,1,2,3]},{type:"narrative",text:"地上散落着断裂的指甲，每一片都指向同一个方向。",effect:"sanityPenalty",val:4,layers:[1,2,3]},{type:"narrative",text:"你看见了自己的背影——不是倒影，它就站在十步之外。",effect:"sanityPenalty",val:8,layers:[2,3]},{type:"narrative",text:"一朵发光的白花从石缝中长出。在这深渊中，生命本身即是奇迹。",effect:"sanity",val:5,layers:[0,1,2,3]},{type:"narrative",text:"脚下的碎石拼成了一行字：『回头。现在还来得及。』",effect:"skip",val:0,layers:[0,1,2,3]},{type:"narrative",text:"石壁上浮现出一段既熟悉又陌生的记忆——那是你第一次握剑的手。",effect:"sanity",val:8,layers:[1,2,3]},{type:"rest",name:"残破的神龛",layers:[0,1,2,3],safe:{text:"静坐祈祷",effect:"sanity",val:18,log:"你感觉心神安定了许多。"},risky:{text:"搜刮供品",effect:"gold",val:50,riskChance:0.3,riskEffect:"cursed_debuff",riskVal:0,log:"供盘中有不少金币。",riskLog:"你感到某种目光落在了背上……下次遇怪概率大幅提升。"}},{type:"rest",name:"地底温泉",layers:[1,2,3],safe:{text:"浸泡疗伤",effect:"heal",val:12,log:"温泉水温润了伤口。"},risky:{text:"搜寻泉底",effect:"material_drop",val:1,riskChance:0.3,riskEffect:"hpLoss",riskVal:8,log:"泉底沉着几块暗铁碎片！",riskLog:"泉水突然沸腾，烫伤了你的腿。"}}];
/* ========== BOSS数据 ========== */
const BOSSES=[
{id:"ratKing",name:"巨鼠之王",layer:0,triggerDepth:18,hpMul:3.0,atkMul:1.5,gold:120,special:"summon",desc:"鼠群之主，身旁永远簇拥着子嗣。"},
{id:"boneGolem",name:"白骨巨像",layer:0,triggerDepth:32,hpMul:5.0,atkMul:1.8,gold:200,special:"boneBurst",desc:"无数骸骨堆砌而成的巨物，每走一步都在崩塌与重组。"},
{id:"mossCorpse",name:"苔衣古尸",layer:0,triggerDepth:48,hpMul:4.0,atkMul:1.3,gold:250,special:"poisonDot",desc:"千年前死去的守望者，如今只是苔藓和怨恨的载体。"},
{id:"shadowAmalgam",name:"暗影聚合体",layer:0,triggerDepth:62,hpMul:3.5,atkMul:2.0,gold:300,special:"splitBoss",desc:"无数迷失灵魂的聚合。打散它——然后面对每一个散落的碎片。"},
{id:"abyssWatcher",name:"深渊窥视者",layer:0,triggerDepth:10,hpMul:2.5,atkMul:2.5,gold:500,special:"torchDrain",desc:"它不是来杀你的。它只是…看着。",hidden:true,spawnCond:"darkness>0.8"}
];
const SKILLS=[{id:"berserk",name:"猛击",desc:"下次攻击伤害×2.5",costType:"sanity",cost:10,type:"nextAttack",buffKey:"berserk",duration:0,value:2.5},{id:"block",name:"格挡",desc:"10秒内防御+6",costType:"sanity",cost:15,type:"buff",buffKey:"block",duration:10,value:6},{id:"flamethrow",name:"点燃投掷",desc:"消耗火把造成火焰伤害",costType:"torch",cost:8,type:"instant",buffKey:null,duration:0,value:0},{id:"focus",name:"凝神屏息",desc:"暂停神智消耗5秒",costType:"none",cost:0,type:"buff",buffKey:"focus",duration:5,value:0,cooldown:30},{id:"allin",name:"孤注一掷",desc:"8秒内暴击率+35%",costType:"hp",cost:20,type:"buff",buffKey:"allin",duration:8,value:0.35},{id:"inspire",name:"振奋",desc:"清除自身减益",costType:"none",cost:0,type:"raceSkill",buffKey:"inspire",duration:0,value:0,cooldown:60,race:"human"},{id:"forestStep",name:"林间步",desc:"触发探索事件",costType:"sanity",cost:10,type:"raceSkill",buffKey:"forestStep",duration:0,value:0,cooldown:120,race:"elf"},{id:"roar",name:"咆哮",desc:"恐惧怪物一回合",costType:"sanity",cost:15,type:"raceSkill",buffKey:"roar",duration:0,value:0,cooldown:45,race:"bear"},{id:"mountainHeart",name:"山之心",desc:"8秒减伤50%",costType:"sanity",cost:20,type:"buff",buffKey:"mountainHeart",duration:8,value:0.5,cooldown:90,race:"dwarf"}];
const BLESSINGS=[{id:"atk",name:"征战祝福",desc:"攻击力 +20%",icon:"⚔️",apply:(s)=>s.atk=Math.round(s.atk*1.2)},{id:"def",name:"坚韧祝福",desc:"生命上限 +20%",icon:"🛡",apply:(s)=>s.maxHp=Math.round(s.maxHp*1.2)},{id:"sanity",name:"清醒祝福",desc:"神智消耗 -35%",icon:"🧠",apply:(s)=>s.sanityResist=Math.min(0.8,s.sanityResist+0.35)},{id:"torch",name:"光明祝福",desc:"火把消耗 -25%",icon:"🕯️",apply:(s)=>s.torchBlessingMul=0.75},{id:"gold",name:"贪婪祝福",desc:"金币获取 +30%",icon:"💰",apply:(s)=>s.goldMul+=0.30},{id:"crit",name:"锐眼祝福",desc:"暴击率 +12%",icon:"👁️",apply:(s)=>s.crit+=0.12}];
const SHOP_ITEMS=[{id:"torch_oil",name:"火把油",desc:"火把恢复+25",icon:"🔥",price:30,maxCarry:3,effect:"torch",value:25},{id:"bandage",name:"急救绷带",desc:"生命恢复+20",icon:"🩹",price:25,maxCarry:2,effect:"heal",value:20},{id:"sedative",name:"镇静药剂",desc:"神智恢复+20",icon:"🧪",price:35,maxCarry:2,effect:"sanity",value:20},{id:"antidote",name:"解毒剂",desc:"移除诅咒debuff",icon:"⚗️",price:20,maxCarry:1,effect:"cleansCurse",value:0},{id:"holy_water",name:"圣水",desc:"下次攻击×1.5",icon:"✨",price:40,maxCarry:1,effect:"holyWater",value:1.5},{id:"firebomb",name:"火药瓶",desc:"造成30点火焰伤害",icon:"💣",price:50,maxCarry:1,effect:"firebomb",value:30}];
const QUEST_POOL=[{id:"kill_rats",name:"清除鼠患",desc:"击败巨鼠",type:"kill",monster:"巨鼠",count:6,gold:100,timeLimit:12},{id:"kill_dogs",name:"白骨猎杀",desc:"击败白骨犬",type:"kill",monster:"白骨犬",count:5,gold:120,timeLimit:14},{id:"depth_20",name:"小试身手",desc:"一次远征中到达20尺深处",type:"depth",target:20,gold:80,timeLimit:15,itemReward:{tid:"rusty_sword"}},{id:"kill_rust",name:"锈蚀之敌",desc:"击败锈甲卫",type:"kill",monster:"锈甲卫",count:4,gold:180,timeLimit:14,needLayer:1},{id:"depth_100",name:"深渊行者",desc:"到达100尺深处",type:"depth",target:100,gold:250,timeLimit:20,itemReward:{tid:"ritual_dagger"}},{id:"kill_shadow",name:"影中猎手",desc:"击败影食者",type:"kill",monster:"影食者",count:3,gold:300,timeLimit:16,needLayer:2},{id:"collect_bones",name:"收集骨片",desc:"在远征中收集3个骨片",type:"collect",material:"骨片",count:3,gold:90,timeLimit:18},{id:"collect_ember",name:"魂火收集",desc:"收集2个魂火余烬",type:"collect",material:"魂火余烬",count:2,gold:150,timeLimit:20,needLayer:1},{id:"survive_5m",name:"坚韧不拔",desc:"在一次远征中持续探索（游戏内5分钟）",type:"survive",minutes:5,gold:130,timeLimit:22},{id:"kill_priest",name:"沉默祭司",desc:"击败无面祭司",type:"kill",monster:"无面祭司",count:2,gold:400,timeLimit:18,needLayer:2,itemReward:{tid:"silver_circlet"}},{id:"depth_200",name:"深层探索",desc:"到达200尺深处",type:"depth",target:200,gold:500,timeLimit:25,needLayer:2},{id:"kill_king",name:"王者陨落",desc:"击败王座囚魂",type:"kill",monster:"王座囚魂",count:1,gold:800,timeLimit:20,needLayer:3,itemReward:{tid:"abyss_edge"}}];
const CRAFT_RECIPES=[{id:"craft_ritual",name:"仪式匕首",result:{tid:"ritual_dagger"},cost:25,materials:[{mid:"bone_shard",qty:3},{mid:"soul_ember",qty:1}],needLayer:0},{id:"craft_chainmail",name:"锁子甲",result:{tid:"chainmail"},cost:20,materials:[{mid:"bone_shard",qty:4}],needLayer:0},{id:"craft_gloves",name:"铁护手",result:{tid:"iron_gauntlets"},cost:18,materials:[{mid:"bone_shard",qty:2},{mid:"soul_ember",qty:1}],needLayer:0},{id:"craft_blessed",name:"祝福长剑",result:{tid:"blessed_blade"},cost:60,materials:[{mid:"dark_iron",qty:3},{mid:"soul_ember",qty:2}],needLayer:1},{id:"craft_iron",name:"铁板铠",result:{tid:"iron_plate"},cost:55,materials:[{mid:"dark_iron",qty:4},{mid:"bone_shard",qty:2}],needLayer:1},{id:"craft_helm",name:"银冠",result:{tid:"silver_circlet"},cost:48,materials:[{mid:"dark_iron",qty:2},{mid:"soul_ember",qty:2}],needLayer:1},{id:"craft_soul",name:"夺魂之镰",result:{tid:"soul_reaper"},cost:150,materials:[{mid:"dark_iron",qty:5},{mid:"abyss_essence",qty:2}],needLayer:2},{id:"craft_bracers",name:"暗影护腕",result:{tid:"shadow_bracers"},cost:110,materials:[{mid:"dark_iron",qty:3},{mid:"abyss_essence",qty:1}],needLayer:2},{id:"craft_cloak",name:"暗影裹尸布",result:{tid:"shadow_shroud"},cost:120,materials:[{mid:"abyss_essence",qty:2},{mid:"soul_ember",qty:3}],needLayer:2},{id:"craft_dragonCloak",name:"不灭之焰",result:{tid:"flame_cloak"},cost:260,materials:[{mid:"ancient_core",qty:2},{mid:"abyss_essence",qty:2}],needLayer:3},{id:"craft_phoenix",name:"凤凰翎羽",result:{tid:"phoenix_feather"},cost:450,materials:[{mid:"ancient_core",qty:3},{mid:"dark_iron",qty:5}],needLayer:3},{id:"craft_abyss_edge",name:"深渊之锋",result:{tid:"abyss_edge"},cost:380,materials:[{mid:"ancient_core",qty:2},{mid:"abyss_essence",qty:4}],needLayer:3}];
const RELICS=[{id:"blade",name:"断裂的军刀",desc:"攻击 +2",apply:h=>h.baseAtk+=2},{id:"mirror",name:"锈蚀护心镜",desc:"防御 +2",apply:h=>h.baseDef+=2},{id:"wax",name:"陈年烛脂",desc:"火把消耗 -8%",apply:h=>h.torchDrainMult*=0.92},{id:"neck",name:"亡者的项链",desc:"神智上限 +15",apply:h=>h.maxSanity+=15},{id:"dice",name:"贪婪的骰子",desc:"金币获取 +10%",apply:h=>h.goldMult*=1.10},{id:"note",name:"缝合的手记",desc:"生命上限 +20",apply:h=>h.maxHp+=20},{id:"coin",name:"幸运银币",desc:"暴击率 +5%",apply:h=>h.critChance+=0.05},{id:"wick",name:"不熄的灯芯",desc:"火把上限 +15",apply:h=>h.maxTorchBonus+=15}];

function freshState(){return{hero:{weaponLvl:0,armorLvl:0,torchLvl:0,baseAtk:8,baseDef:2,maxHp:50,hp:50,maxSanity:100,sanity:100,maxTorchBonus:0,torchDrainMult:1,goldMult:1,critChance:0.05,sanityResist:0,darkPower:0,revive:0,baseDodge:0,eventRewardMul:1,smithCostMul:1,race:"human"},gold:0,maxDepthRecord:0,bestiary:{},relicsOwned:{},inventory:[],equipment:{weapon:null,head:null,body:null,hands:null,waist:null,feet:null,cloak:null,relic:null},equipSlots:4,bagCapacity:20,activeQuests:[],completedQuestIds:[],questRefreshAt:0,unlockedLayers:[0],selectedLayer:0,unlockedRaces:["human"],craftsMade:0,prayerCooldown:0,activeBlessing:null,warehouse:[],warehouseSlots:20,expedition:{active:false,depth:0,maxDepthReached:0,torch:100,maxTorch:100,monster:null,carriedGold:0,layerIndex:0,itemsFound:[],surviveMinutes:0,surviveTick:0,event:null,skillCooldowns:{},activeBuffs:{},consumables:{},_expeditionEvents:0,bossKilled:[]},lastTs:Date.now(),logs:[]}}

function load(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return freshState();const parsed=JSON.parse(raw);const fresh=freshState();const merged=Object.assign(fresh,parsed,{hero:Object.assign(fresh.hero,parsed.hero||{}),equipment:Object.assign(fresh.equipment,parsed.equipment||{}),expedition:Object.assign(fresh.expedition,parsed.expedition||{})});if(!merged.equipment)merged.equipment={weapon:null,head:null,body:null,hands:null,waist:null,feet:null,cloak:null,relic:null};if(merged.equipment.armor!==undefined&&merged.equipment.body===undefined){merged.equipment.body=merged.equipment.armor||null;delete merged.equipment.armor}if(merged.equipment.accessory1!==undefined){if(!merged.equipment.relic)merged.equipment.relic=merged.equipment.accessory1||null;delete merged.equipment.accessory1}if(merged.equipment.accessory2!==undefined){merged.inventory=merged.inventory||[];if(merged.equipment.accessory2)merged.inventory.push(merged.equipment.accessory2);delete merged.equipment.accessory2}["head","hands","waist","feet","cloak"].forEach(k=>{if(!(k in merged.equipment))merged.equipment[k]=null});if(merged.equipSlots===undefined||merged.equipSlots<4)merged.equipSlots=4;if(merged.bagCapacity===undefined)merged.bagCapacity=20;if(merged.prayerCooldown===undefined)merged.prayerCooldown=0;if(merged.activeBlessing===undefined)merged.activeBlessing=null;if(!merged.warehouse)merged.warehouse=[];if(merged.warehouseSlots===undefined)merged.warehouseSlots=20;if(!merged.activeQuests)merged.activeQuests=[];if(!merged.unlockedLayers)merged.unlockedLayers=[0];if(!merged.selectedLayer)merged.selectedLayer=0;
    if(!merged.unlockedRaces)merged.unlockedRaces=["human"];if(merged.craftsMade===undefined)merged.craftsMade=0;if(!merged.questRefreshAt)merged.questRefreshAt=0;if(!merged.completedQuestIds)merged.completedQuestIds=[];if(merged.expedition&&merged.expedition.maxDepthReached===undefined)merged.expedition.maxDepthReached=0;if(merged.expedition&&merged.expedition.itemsFound===undefined)merged.expedition.itemsFound=[];if(merged.expedition&&merged.expedition.surviveTick===undefined)merged.expedition.surviveTick=0;if(!merged.hero.race)merged.hero.race="human";if(merged.hero.baseDodge===undefined)merged.hero.baseDodge=0;if(merged.hero.eventRewardMul===undefined)merged.hero.eventRewardMul=1;if(merged.hero.smithCostMul===undefined)merged.hero.smithCostMul=1;return merged}catch(e){return freshState()}}
function save(){if(S._deleting)return;S.lastTs=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(S))}
function el(id){return document.getElementById(id)}

/* ========== 种族数据 ========== */
function freshState(){return{hero:{weaponLvl:0,armorLvl:0,torchLvl:0,baseAtk:8,baseDef:2,maxHp:50,hp:50,maxSanity:100,sanity:100,maxTorchBonus:0,torchDrainMult:1,goldMult:1,critChance:0.05,sanityResist:0,darkPower:0,revive:0,baseDodge:0,eventRewardMul:1,smithCostMul:1,race:"human"},gold:0,maxDepthRecord:0,bestiary:{},relicsOwned:{},inventory:[],equipment:{weapon:null,head:null,body:null,hands:null,waist:null,feet:null,cloak:null,relic:null},equipSlots:4,bagCapacity:20,activeQuests:[],completedQuestIds:[],questRefreshAt:0,unlockedLayers:[0],selectedLayer:0,unlockedRaces:["human"],craftsMade:0,prayerCooldown:0,activeBlessing:null,warehouse:[],warehouseSlots:20,expedition:{active:false,depth:0,maxDepthReached:0,torch:100,maxTorch:100,monster:null,carriedGold:0,layerIndex:0,itemsFound:[],surviveMinutes:0,surviveTick:0,event:null,skillCooldowns:{},activeBuffs:{},consumables:{},_expeditionEvents:0,bossKilled:[]},lastTs:Date.now(),logs:[]}}

function load(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return freshState();const parsed=JSON.parse(raw);const fresh=freshState();const merged=Object.assign(fresh,parsed,{hero:Object.assign(fresh.hero,parsed.hero||{}),equipment:Object.assign(fresh.equipment,parsed.equipment||{}),expedition:Object.assign(fresh.expedition,parsed.expedition||{})});if(!merged.equipment)merged.equipment={weapon:null,head:null,body:null,hands:null,waist:null,feet:null,cloak:null,relic:null};if(merged.equipment.armor!==undefined&&merged.equipment.body===undefined){merged.equipment.body=merged.equipment.armor||null;delete merged.equipment.armor}if(merged.equipment.accessory1!==undefined){if(!merged.equipment.relic)merged.equipment.relic=merged.equipment.accessory1||null;delete merged.equipment.accessory1}if(merged.equipment.accessory2!==undefined){merged.inventory=merged.inventory||[];if(merged.equipment.accessory2)merged.inventory.push(merged.equipment.accessory2);delete merged.equipment.accessory2}["head","hands","waist","feet","cloak"].forEach(k=>{if(!(k in merged.equipment))merged.equipment[k]=null});if(merged.equipSlots===undefined||merged.equipSlots<4)merged.equipSlots=4;if(merged.bagCapacity===undefined)merged.bagCapacity=20;if(merged.prayerCooldown===undefined)merged.prayerCooldown=0;if(merged.activeBlessing===undefined)merged.activeBlessing=null;if(!merged.warehouse)merged.warehouse=[];if(merged.warehouseSlots===undefined)merged.warehouseSlots=20;if(!merged.activeQuests)merged.activeQuests=[];if(!merged.unlockedLayers)merged.unlockedLayers=[0];if(!merged.selectedLayer)merged.selectedLayer=0;
    if(!merged.unlockedRaces)merged.unlockedRaces=["human"];if(merged.craftsMade===undefined)merged.craftsMade=0;if(!merged.questRefreshAt)merged.questRefreshAt=0;if(!merged.completedQuestIds)merged.completedQuestIds=[];if(merged.expedition&&merged.expedition.maxDepthReached===undefined)merged.expedition.maxDepthReached=0;if(merged.expedition&&merged.expedition.itemsFound===undefined)merged.expedition.itemsFound=[];if(merged.expedition&&merged.expedition.surviveTick===undefined)merged.expedition.surviveTick=0;if(!merged.hero.race)merged.hero.race="human";if(merged.hero.baseDodge===undefined)merged.hero.baseDodge=0;if(merged.hero.eventRewardMul===undefined)merged.hero.eventRewardMul=1;if(merged.hero.smithCostMul===undefined)merged.hero.smithCostMul=1;return merged}catch(e){return freshState()}}
function save(){if(S._deleting)return;S.lastTs=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(S))}
function el(id){return document.getElementById(id)}

/* ========== 种族数据 ========== */
